server:
  port: 8080         # 포트 번호 (기본값이지만 명시적으로 적어줌)
  address: 0.0.0.0   # 외부 IP에서 접근 가능하게

spring:
  datasource:
    url: jdbc:mysql://3.37.146.121:3306/hospital_data
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
