server:
  port: 8080  # 유저 서비스 포트
  address: 0.0.0.0   # 외부 IP에서 접근 가능하게

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}

spring:
  web:
    resources:
      static-locations: file:uploads/, classpath:/static/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 애플리케이션 실행 시 DB 자동 생성
    show-sql: true  # 콘솔에 SQL 출력
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1시간 (밀리초 단위)