server:
  port: 8080

spring:
  cloud:
    gateway:
      #      corsConfigurations:
      #        '[/**]':  # ?? ??? ?? CORS ??
      #          allowedOrigins: "http://localhost:3000"  # ?????? ??? ?? ??
      #          allowedMethods:
      #            - GET
      #            - POST
      #            - PUT
      #            - DELETE  # ??? HTTP ???
      #          allowedHeaders:
      #            - "*"
      #          allowCredentials: true

      routes:
        - id: community-service
          uri: http://localhost:8082/  # ?? ??? URI
          predicates:
            - Path=/api/community/**  # /api/community/** ??? ???? ??? ? ???? ??
