server:
  port: 8080

spring:
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders:
#              - "*"
#            allowCredentials: true

      routes:
        - id: community-service-post
          uri:  http://ec2-3-36-161-179.ap-northeast-2.compute.amazonaws.com:8082
          predicates:
            - Path=/post/**
          filters:
            - RewritePath=/post/(?<path>.*), /post/\${path}  # << 여기가 핵심!

        - id: community-service-comment
          uri:  http://ec2-3-36-161-179.ap-northeast-2.compute.amazonaws.com:8082
          predicates:
              - Path=/comment/**
          filters:
              - RewritePath=/comment/(?<path>.*), /comment/\${path}
